<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="pond.jfrog.org" name="org.artifactory.util.ExceptionUtilsTest" tests="4" failures="0" timestamp="13 May 2013 13:10:47 GMT" time="0.003" errors="0">
  <testcase name="testGetRootCauseNotNested" time="0.000" classname="org.artifactory.util.ExceptionUtilsTest"/>
  <testcase name="testUnwrapThrowablesOfTypes" time="0.001" classname="org.artifactory.util.ExceptionUtilsTest"/>
  <testcase name="testGetRootCauseNested" time="0.001" classname="org.artifactory.util.ExceptionUtilsTest"/>
  <testcase name="testGetCauseOfTypes" time="0.001" classname="org.artifactory.util.ExceptionUtilsTest"/>
</testsuite> <!-- org.artifactory.util.ExceptionUtilsTest -->
